# SPDX-FileCopyrightText: 2024 Jomco B.V.
# SPDX-FileCopyrightText: 2024 Topsector Logistiek
# SPDX-FileContributor: Joost Diepenmaat <joost@jomco.nl
# SPDX-FileContributor: Remco van 't Veer <remco@jomco.nl>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# build.sr.ht

image: alpine/latest

packages:
  - openssl
  - openjdk11-jre-headless

sources:
  - https://git.sr.ht/~jomco/connekt-dil-demo

tasks:
  - clojure: |
      curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
      sh linux-install.sh -p `pwd`
  - check: |
      PATH=$PATH:`pwd`/bin
      cd connekt-dil-demo
      make check
