# SPDX-FileCopyrightText: 2025 Topsector Logistiek
# SPDX-FileCopyrightText: 2025 Jomco B.V.
# SPDX-FileContributor: Joost Diepenmaat <joost@jomco.nl>
# SPDX-FileContributor: Remco van 't Veer <remco@jomco.nl>
# SPDX-License-Identifier: AGPL-3.0-or-later

suppression.file=.nvd-suppressions.xml

