# SPDX-FileCopyrightText: 2024 Jomco B.V.
# SPDX-FileCopyrightText: 2024 Topsector Logistiek
# SPDX-FileContributor: Joost Diepenmaat <joost@jomco.nl>
# SPDX-FileContributor: Remco van 't Veer <remco@jomco.nl>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

.PHONY: config test clean

config:
	$(MAKE) -C config

test:
	$(MAKE) -C bdi-stack test
	$(MAKE) -C vgu-demo test

clean:
	$(MAKE) -C config clean
